#!/usr/bin/env bash
# This script displays a list of currently running processes with process hierarchy.

# Display all processes for all users, including those without a TTY, in a user-oriented format
ps auxf
