#!/usr/bin/env bash
# Starting 100-process_and_pid_file in the terminal #0 and then kill it in the terminal #1.

file="/var/run/myscript.pid"

if [ ! -e "$file" ]; then
	touch "$file"
fi

sleep 2 &

echo "$!" > "$file"

# prints I hate the kill command, deletes the file and exits  when receiving a SIGTERM or SIGQUIT signal
trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM SIGQUIT

# prints Y U no love me?! when receiving a SIGINT signal
trap "echo Y U no love me?!" SIGINT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
