#!/usr/bin/env bash
# This script displays lines containing the word "bash" to get the PID of the Bash process.

# shellcheck disable=SC2009
# Display lines containing the word "bash" from the output of the ps command
ps aux | grep bash
