#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and shows specific messages for certain iterations using the case statement.

# Initialize a counter
counter=1

# Use a while loop to iterate from 1 to 20
while [ $counter -le 20 ]
do
	# Use the case statement to display different messages based on the iteration
	case $counter in
	4)
		echo "$counter and then bad luck from China"
		;;
	9)
		echo "$counter and then bad luck from Japan"
		;;
	17)
		echo "$counter and then bad luck from Italy"
		;;
	*)
		echo $counter
		;;
	esac
    
	((counter++))
done
